###
POST http://localhost:3001/login/auth HTTP/1.1
Content-Type: application/json

{
    "email": "danilo@gmail.com",
    "password": "donado1234"
}


###
POST http://localhost:3001/inform/register HTTP/1.1
Content-Type: application/json

{
    "cedula": "322123422",
    "nombre": "danilo",
    "apellido": "donado",
    "email": "danilo@gmail.com",
    "password": "donado1234",
    "sex": "male",
    "fecha": "12-04-1999",
    "idroles": 1,
    "idMenbrecia": 1,
    "numero": "2321321321",
    "nombreTarjeta": "danilo donado",
    "cvv": "123",
    "fechaExpiracion": "12/23"
}


###

GET http://localhost:3001/datos/basicos/danilo@gmail.com HTTP/1.1
